global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
- '/etc/prometheus/alert-rules.yml'

scrape_configs:

# Prometheus se monitorea a sí mismo
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

# Backend Spring Boot — métricas de la aplicación (THAQHIRI)
# REEMPLAZAR IP: output de Terraform → ec2_private_ip (instancia thaqhiri-dev-app)
- job_name: 'thaqhiri-backend'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 15s
  static_configs:
  - targets: [ '10.0.1.85:5511' ]
    labels:
      environment: 'dev'
      service: 'thaqhiri-backend'

# Node Exporter de la EC2 monitoring-core (esta misma instancia)
- job_name: 'node-exporter-monitoring-core'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
    labels:
      environment: 'dev'
      instance_role: 'monitoring-core'

# Node Exporter de la EC2 app (backend)
# REEMPLAZAR IP: output de Terraform → ec2_private_ip (instancia thaqhiri-dev-app)
- job_name: 'node-exporter-app'
  static_configs:
  - targets: [ '10.0.1.85:9100' ]
    labels:
      environment: 'dev'
      instance_role: 'app'

# Node Exporter de la EC2 monitoring-logs
# REEMPLAZAR IP: output de Terraform → monitoring_logs_private_ip (instancia thaqhiri-dev-monitoring-logs)
- job_name: 'node-exporter-monitoring-logs'
  static_configs:
  - targets: [ '10.0.1.92:9100' ]
    labels:
      environment: 'dev'
      instance_role: 'monitoring-logs'
