apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    # REEMPLAZAR con IP privada de la instancia thaqhiri-dev-monitoring-logs
    url: http://10.0.1.92:3100
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger
    # REEMPLAZAR con IP privada de la instancia thaqhiri-dev-monitoring-logs
    url: http://10.0.1.92:16686
    editable: true
